apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7
        volumeMounts:
          - name: redis-persistance-storage
            mountPath: /data
        ports: 
          - containerPort: 6379
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        env: 
          - name: REDIS_HOSTS
            value: microk8s:localhost:6379
        ports: 
          - containerPort: 8081
      volumes: 
        - name: redis-persistance-storage
          hostPath: 
            path: /mnt/redis/data
            type: DirectoryOrCreate


