apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - name: tcp
      port: 6379
      nodePort: 30080
      protocol: TCP
    - name: http
      port: 8081
      nodePort: 30081
      protocol: TCP
  type: NodePort
