apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-chart.fullname" . }}
  labels:
    {{- include "redis-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.redisPort }}
      protocol: TCP
      nodePort: {{ .Values.service.redisNodePort }}
      name: tcp
    - port: {{ .Values.service.redisCommanderPort }}
      protocol: TCP
      nodePort: {{ .Values.service.redisCommanderNodePort }}
      name: http
  selector:
    {{- include "redis-chart.selectorLabels" . | nindent 4 }}
